name: crypto_wallet
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  aes_crypt_null_safe: ^3.0.0
  bip39: ^1.0.6
  clipboard: ^0.1.3
  cs_ui:
    path: packages/cs_ui
  dotted_border: ^2.0.0+1
  ed25519_hd_key: ^2.3.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.4
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.3.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.9
  hex: ^0.2.0
  http: ^1.2.1
  intl: ^0.19.0
  local_auth: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.5.3
  web3dart: ^2.6.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/abi/
    - assets/icons/
    - assets/.env
    - assets/fonts/

dependency_overrides:
  intl: ^0.19.0
